# Generated by Django 2.2.7 on 2019-11-06 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=80, null=True, verbose_name='The answer')),
                ('has_transition', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=600, verbose_name='What do you want to ask?')),
                ('answers', models.ManyToManyField(related_name='question_asked', to='api.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transition_next', to='api.Question')),
                ('previous_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transition_prev', to='api.Question')),
                ('selected_answer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transition_ans', to='api.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_name', models.CharField(max_length=350, verbose_name='Conversation objective')),
                ('start_question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='api.Question')),
            ],
        ),
    ]
